/**
 * Projects sidebar configuration
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const projectsSidebar = {
  // Projects sidebar - the key here should match the plugin ID
  projects: [{ type: "autogenerated", dirName: "." }],
};

export default projectsSidebar;
