/**
 * Projects sidebar configuration
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarProjects = {
  projectsSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

module.exports = sidebarProjects;
